config_version = 3

[chat]
    # enable global chat?
    enable = true

    # should the chat messages be echoed to velocity's console?
    log_to_console = false

    # should chat messages be passed through to the minecraft server?
    # if enabled, it will show duplicate messages in the senders chat
    #WARNING! THIS WILL PASSTHROUGH UNFILTERED CHAT!
    passthrough = false

    # should chat messages be parsed through minimessage?
    # player will be able to use styles such as <rainbow>hello</rainbow> in their messages
    # parse_player_messages = false

    # global chat format, you can use minimessage tags here.
    format = "%lp_prefix%%player%%lp_suffix%&r: %message%"

[switch]
    # send a chat message when a player switches servers
    enable = false
    format = "&c<player> moved to <server>"

[filter]
    #Want to add/remove what words at blocked? Check out blocked-words.txt
    enable = true
    blocked-msg = "Sorry, your message contains a blacklisted word."
    blocked-actionbar = "Hey, your message contains a blacklisted word."
    #If set to true it will add your text instead of simply blocking the message
    censor = false
    censor-msg = "kittens"
